
spring:
  application:
    name: jamo-proxy
  lifecycle:
    timeout-per-shutdown-phase: 60s

info:
  application:
    name: jamo-proxy

server:
  max-http-header-size: 20000
  shutdown: graceful

management:
  info:
    env:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
logging.level.springfox.documentation: DEBUG

