
spring:
  application:
    name: jamo-proxy

info:
  application:
    name: jamo-proxy

management:
  info:
    env:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
logging.level.springfox.documentation: DEBUG