
spring:
  application:
    name: jamo-proxy

info:
  application:
    name: jamo-proxy

server:
  max-http-header-size: 20000

management:
  info:
    env:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"
logging.level.springfox.documentation: DEBUG

